name:                TIMConvert
version:             0.0.0.0
#synopsis:
#description:
#homepage:            https://github.com/githubuser/TIMConvert#readme
license:             BSD3
author:              Sridhar Ramesh
#maintainer:          example@example.com
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  TIMConvert:
    source-dirs:      src
    main:             Main.hs
