name:                TIMConvert
version:             0.0.0.0
#synopsis:
#description:
#homepage:            https://github.com/githubuser/TIMConvert#readme
license:             BSD3
author:              Sridhar Ramesh
#maintainer:          example@example.com
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - binary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  TIMConvert:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    # I don't know if any of these are important. 
    # They're in other templates, but not the simple-hpack one, I guess?
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    when:
      # To prevent warning noted at https://github.com/commercialhaskell/stack/issues/5439
      - condition: false
        other-modules: Paths_TIMConvert
